like = input("Things you like: ")
print()
hate = input("Things you hate: ")
print()
family_friend = input("Names of family and friends: ")
print()
print("You like", like, "and you hate", hate, "and you have a family and friends", family_friend)
print()
print("Welcome to your adventure simulator. I am going to ask you a bunch of questions and then create an epic story with you as the star!")
print()
name = input("What is your name?: ")
print()
enemy = input("What is your worst enemy’s name?: ")
print()
superpower = input("What is your superpower?: ")
print()
live_in = input("Where do you live?: ")
print()
fav_food = input("What is your favorite food?: ")
print()
print("Hello", name, "Your ability to", superpower, "will make sure you never have to look at", enemy, "again. Go eat", fav_food, "as you walk down the streets of", live_in, "and use", superpower, "for good and not evil!")
